export const RECEIVE_ACCOUNT = "RECEIVE_ACCOUNT";
export type RECEIVE_ACCOUNT = typeof RECEIVE_ACCOUNT;
export const REQUEST_ACCOUNT = "REQUEST_ACCOUNT";
export type REQUEST_ACCOUNT = typeof REQUEST_ACCOUNT;
export const LOG_ACCOUNT_ERROR = "LOG_ACCOUNT_ERROR";
export type LOG_ACCOUNT_ERROR = typeof LOG_ACCOUNT_ERROR;



export const RECEIVE_AUTH_USER = "RECEIVE_AUTH_USER";
export type RECEIVE_AUTH_USER = typeof RECEIVE_AUTH_USER;
export const LOG_AUTH_ERROR = "LOG_AUTH_ERROR";
export type LOG_AUTH_ERROR = typeof LOG_AUTH_ERROR;
export const REQUEST_AUTH_USER = "REQUEST_AUTH_USER";
export type REQUEST_AUTH_USER = typeof REQUEST_AUTH_USER;
export const SIGNOUT_USER = "SIGNOUT_USER";
export type SIGNOUT_USER = typeof SIGNOUT_USER;


export const TOGGLE_NOTIFICATION = "TOGGLE_NOTIFICATION";
export type TOGGLE_NOTIFICATION = typeof TOGGLE_NOTIFICATION;